server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true   #优先使用服务 ip 进行注册
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          default:
            # 连接超时时间
            connect-timeout: 20000
            # 读取超时时间
            read-timeout: 20000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          min-request-size: 2048  # 最小触发压缩的大小
          mime-types: text/html, application/xml, application/json  #触发压缩的数据类型
        response:
          enabled: true

      circuitbreaker:
        enabled: true
#        group:
#          enabled: true

# feign 日志以什么级别监控哪个接口
#logging:
#  level:
#    com:
#      atguigu:
#        cloud:
#          apis:
#            PayFeignApi: debug

# 基于次数的降级
#resilience4j:
#  circuitbreaker: # 降级熔断
#    configs:
#      default:
#        failure-rate-threshold: 50 # 调用失败达到50%后打开断路器
#        sliding-window-type: count_based # 滑动窗口类型
#        sliding-window-size: 6 # 滑动窗口大小 count_based6个请求 time_base6秒
#        minimum-number-of-calls: 6 # 每个滑动窗口的周期
#        automatic-transition-from-open-to-half-open-enabled: true # 开始过度到半开状态
#        wait-duration-in-open-state: 5s # 从开启到半开启需要5s
#        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许通过的最大请求数
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        baseConfig: default

# 基于慢调用的降级
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s 超过1s直接降级 (坑)
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50 # 调用失败达到50%后打开断路器
#        slow-call-duration-threshold: 2s # 慢调用时间阈值
#        slow-call-rate-threshold: 30 # 慢调用百分比峰值
#        sliding-window-type: time_based # 滑动窗口类型
#        sliding-window-size: 2 # 滑动窗口大小 count_based6个请求 time_base6秒
#        minimum-number-of-calls: 2 # 每个滑动窗口的周期
#        automatic-transition-from-open-to-half-open-enabled: true # 开始过度到半开状态
#        wait-duration-in-open-state: 5s # 从开启到半开启需要5s
#        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许通过的最大请求数
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        base-config: default

# 隔离策略
#resilience4j:
#  bulkhead:
#    configs:
#      default:
#        maxConcurrentCalls: 2  # 隔离允许并发线程执行的最大数量
#        maxWaitDuration: 1s  # 隔离允许等待的最大时间
#    instances:
#        cloud-payment-service:
#          baseConfig: default
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 20s


# resilience4j bulkhead -THREADPOOL的例子
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s 超过1s直接降级 (坑)
#  thread-pool-bulkhead:
#    configs:
#      default:
#        core-thread-pool-size: 1
#        max-thread-pool-size: 1
#        queue-capacity: 1
#    instances:
#      cloud-payment-service:
#        base-config: default

# resilience4j ratelimiter 限流的例子
#resilience4j:
#  ratelimiter:
#    configs:
#      default:
#        limit-for-period: 2 # 在一次刷新周期内，允许执行的最大请求数
#        limitRefreshPeriod: 1s # 刷新周期
#        timeout-duration: 1 # 线程等待权限的默认时间
#    instances:
#        cloud-payment-service:
#          baseConfig: default


#  zipkin
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0  # 采样率默认为0.1
