server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos地址
    sentinel:
      transport:
        dashboard: localhost:8080   # sentinel dashboard地址
        port: 8719  # 默认8719，如果被占用，会依次+1扫描
