server:
  port: 8401

spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos 服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080   # 配置sentinel dashboard地址
        port: 8719 # 默认端口
      web-context-unify: false  # controller 层的方法对service层调用不认为是同一个根链路
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
